/* LUMEN — AI insight page */
(function (LUMEN) {
  "use strict";

  const { $, fill, duration, esc } = LUMEN.ui;
  const api = LUMEN.api;

  const el = {
    signals: $("[data-signals]"),
    mix: $("[data-mix]"),
    source: $("[data-insight-source]")
  };

  function signal(label, value, note) {
    return (
      "<div>" +
        '<p class="signal__label">' + esc(label) + "</p>" +
        '<p class="signal__value">' + esc(value) + "</p>" +
        '<p class="signal__note">' + esc(note) + "</p>" +
      "</div>"
    );
  }

  function renderSignals(week, today) {
    if (!el.signals) return;

    if (!week) {
      el.signals.innerHTML =
        '<p class="empty">These numbers could not be loaded.</p>';
      return;
    }

    const sign =
      week.deltaPercent > 0
        ? "+"
        : week.deltaPercent < 0
        ? "−"
        : "";

    el.signals.innerHTML = [
      signal(
        "Focused time",
        duration(week.totalSeconds),
        week.deltaPercent === 0
          ? "same as last week"
          : sign +
              Math.abs(week.deltaPercent) +
              "% vs last week"
      ),

      signal(
        "Sessions",
        String(week.sessions),
        week.completedSessions +
          " finished, " +
          week.abandonedSessions +
          " cut short"
      ),

      signal(
        "Completion rate",
        week.completionRate + "%",
        "share of sessions run to the end"
      ),

      signal(
        "Average session",
        duration(week.averageSessionSeconds),
        "across this week"
      ),

      today
        ? signal(
            "Current streak",
            today.streakDays +
              (today.streakDays === 1 ? " day" : " days"),
            "personal best: " +
              Math.max(
                today.bestStreakDays,
                today.streakDays
              )
          )
        : ""
    ].join("");
  }

  function renderMix(mix) {
    if (!el.mix) return;

    if (!mix || !mix.length) {
      el.mix.innerHTML =
        '<p class="empty">No completed sessions in the last 28 days yet.</p>';
      return;
    }

    el.mix.innerHTML = mix
      .map(function (m) {
        return (
          '<div class="mix__row">' +
            '<div class="mix__head">' +
              "<span>" +
              esc(m.label) +
              "</span>" +
              "<span>" +
              esc(m.percent) +
              "%</span>" +
            "</div>" +
            '<div class="mix__track">' +
              '<div class="mix__fill" style="width:' +
              Number(m.percent) +
              '%"></div>' +
            "</div>" +
          "</div>"
        );
      })
      .join("");
  }

  function renderSource(insight) {
    if (!el.source) return;

    if (insight && insight.source === "openai") {
      el.source.textContent = "✦ Generated by LUMEN AI";
      el.source.removeAttribute("hidden");
      return;
    }

    if (insight && insight.source === "local") {
      el.source.textContent = "Waiting for enough focus data";
      el.source.removeAttribute("hidden");
      return;
    }

    el.source.textContent = "";
  }

  Promise.allSettled([
    api.insight(),
    api.weekly(),
    api.dailyStats(),
    api.sessionMix()
  ]).then(function (results) {
    const value = (i) =>
      results[i].status === "fulfilled"
        ? results[i].value
        : null;

    const insight = value(0);
    const week = value(1);
    const today = value(2);
    const mix = value(3);

    if (insight) {
      fill({
        "insight-title": insight.title,
        "insight-body": insight.body
      });

      renderSource(insight);
    } else {
      fill({
        "insight-title": "LUMEN AI is unavailable",
        "insight-body":
          "The AI service could not generate an insight right now. Check the backend logs for the API error."
      });

      renderSource(null);
    }

    if (week) {
      fill({
        "range-label": week.range
      });
    }

    renderSignals(week, today);
    renderMix(mix);
  });
})(window.LUMEN);